### ISSUE TITLE
clean colab notebook

### ISSUE THREAD

**Issue by LaverdeS** [LaverdeS/Multivariate-Time-Series-Classification#6]
Some figures in the [notebook](https://colab.research.google.com/drive/1cmEeaysFMeBgyP3u8Im4nkdr-OXfssNn#scrollTo=KolVQlXr-WtL) are displayed twice. The return for `plot_outliers_in` is a figure that should be wrapped around plt.show() to avoid this.

**Comment by Soumya-Kushwaha** [comment]
Can you please help me with this error?
![image](https://user-images.githubusercontent.com/87495134/217682887-2db17339-38b7-4969-a3b6-410bf797869e.png)

**Comment by LaverdeS** [comment]
Hi @Soumya-Kushwaha 🎊! For now, if you are running a jupyter locally, you would have to move the notebook to the [python](https://github.com/LaverdeS/Multivariate-Time-Series-Classification/tree/main/python) folder to debug, or open it on google colab and upload the [3 python scripts](https://github.com/LaverdeS/Multivariate-Time-Series-Classification/tree/main/python) there. Nevertheless, I just realised that you will face other errors because you don't have sample data to test it with. It will be on a sample-data folder soon! I will be sure to ping you when is there. Thank you for your interest!

**Comment by Soumya-Kushwaha** [comment]
Alright.
I'll be happy to contribute whenever possible!

**Comment by LaverdeS** [comment]
Hi @Soumya-Kushwaha! 
- I created a [sample-data/tinder](https://github.com/LaverdeS/Multivariate-Time-Series-Classification/tree/main/sample-data/tinder) folder with some `.json` files that the notebook uses. The dataset is part of a pending publication so I just shared 20% of it and I kindly ask you to keep that in mind 🤗.
- I preferred to create a google colab that installs the repo so you can just run every cell without any path-related issues. [Here](https://colab.research.google.com/drive/1cmEeaysFMeBgyP3u8Im4nkdr-OXfssNn#scrollTo=KolVQlXr-WtL) is the link (_all notebook links for this issue have been also updated_). 
- Your gmail account has been granted edit permissions so you can simply make the necessary changes in the colab and paste a snippet of the solution(s) in a Pull Request (you can create a new branch but are not forced to). Name the PR/branch however you want.
- You need to do changes in two cells inside the `OUTLIER DETECTION + REMOVAL USING IQR > Lenghts` section of the notebook.

**Comment by Soumya-Kushwaha** [comment]
@LaverdeS I tried but seems like I am unable to help you here. I can't understand what should be done to avoid those double plots.
I believe I may contribute some other time!

**Comment by LaverdeS** [comment]
@Soumya-Kushwaha No problem, there are some other issues if you are interested. You can always write me a comment if you need help or me to clarify the task. Thanks again for your interest.

-- The issue has been closed, colab notebook is now updated wrapping figures with `plt.show(--figure--)`
